version: "3"
services:
  api:
    container_name: vinopinions-api
    image: ghcr.io/layla-oskar-schule/vinopinionsapi-staging:latest 
    env_file:
      - .env
    depends_on:
      - postgres
    networks:
      - internal
      - server
  postgres:
    container_name: vinopinionsapi-db
    image: postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PORT=${POSTGRES_PORT}
    volumes:
      - vinopinionsapi-db:/var/lib/postgresql/data
    networks:
      - internal
networks:
  server:
    external: true
  internal:
      internal: true
volumes:
  vinopinionsapi-db:
